cypress/tests/meta.cy.ts, src/index.html
Change title to something more better matching.
Title used be react boilerplate title.
Minor change to static content.
There is a e2e test included which tests this in the future.
No
=> Use right title

src/login/index.html
=> login page accessibility

src/features/Footer/Footer.tsx
Fixed the footer to stick to the bottom of the page even when the content scrolls
No special test for this change
=> Fixed the footer to stick to the bottom

cypress/tests/login.cy.ts, cypress/tests/register.cy.ts, src/register/index.html, src/register/index.js, src/register/styles.css
=> Add password confirmation field and refactor static pages e2e tests

cypress/tests/register.cy.ts, src/register/index.js
=> Fix password field bug and tests

cypress/tests/register.cy.ts, src/register/index.html, src/register/index.js
This PR allows a user to create an account and use it to log in to the application.
**In the future, we should improve the e2e tests to test the full path of creating an account, logging in and then deleting the account.**
=> Registration page api calls

src/login/styles.css
Fixes invalid font used in the input fields on the Login page.
This was made to fix a bug.
=> Fix login page font

README.md, cypress/support/commands.ts, cypress/tests/register.cy.ts, package.json, src/login/index.html, src/register/index.html, src/register/index.js, src/register/styles.css
Fixes:
- [Validate username from server and show error notification](https://trello.com/c/GCRXqKrv/671-registration-page-validate-username-from-server-and-show-error-notification)
- [Length validations for registration form fields](https://trello.com/c/PnlcOYgq/700-length-validations-for-registration-form-fields)
- [Password field validations](https://trello.com/c/tbGGIIHW/702-password-field-validations)
- [Generic Network Error](https://trello.com/c/oEudB7tz/706-generic-network-error)
We want to tell the user to edit invalid fields sending the form. We also want to explain why. This improves user experience.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant …
=> Registration form validations

src/register/index.html
=> Update registration display name info text

src/register/styles.css
Fixes https://trello.com/c/nPy2creq/708-fix-registration-page-info-box-styling
This change makes the registration page info boxes adhere to the design.
=> Update info box styling to satisfy the design

src/components/Text/variants.ts, src/components/variables.ts, src/features/Navigation/InfoDropdown/DropdownButton.tsx, src/features/Navigation/InfoDropdown/InfoItem.tsx, src/features/Navigation/InfoDropdown/index.tsx, src/features/Navigation/LanguageDropdown/LangItem.tsx, src/features/Navigation/LanguageDropdown/index.tsx, src/features/Navigation/LogoContainer.tsx, src/features/Navigation/MobileDropdown/MobileLangItem.tsx, src/features/Navigation/MobileDropdown/MobileNavItem.tsx, src/features/Navigation/MobileDropdown/index.tsx, src/features/Navigation/Navbar.tsx, src/features/Navigation/NavigationItems.tsx, src/hooks/useHover.ts, src/test/setup.ts
Style adjustments found in last sprint-planning session, fixes issues in following [Trello-card](https://trello.com/c/mIWzlnBv/758-small-style-fixes-for-navigation)
- Make the designs more close to the designs, 
- Remove i18n-warnings from jest-tests
- Refactor code for better readability and follow project conventions
Ran jest tests, and tsc
- Small refactoring, created two new components for logic abstraction.
- One new hook, useHover. I opted to use a hook for hovering because it was easiest and most readable way (I figured out fast enough ) to fix the fill-property for the icon-component on hover-effect.
=> Navigation style-adjustments

src/features/Chat/chatPageApi.ts, src/features/Chat/chatSlice.ts, src/features/Chat/components/Window/Message.tsx, src/features/Chat/components/Window/MessageList.tsx, src/features/MentorPage/components/MentorList/MentorCard/Expanded/Content.tsx
I wanted to "finalise" quickly a bit this messaging-feature, meaning that the happy path works.
So brought two smaller functionalities:
- Can mark message as seen ( sent message wont appear as not seen )
- Can start a new converstation from the MentorCard!
I had a feeling in the back of my head that I needed to fix this, so the feature does not feel so incomplete =P
=> New chat, mark seen

src/features/MentorPage/components/MentorList/MentorCard/Expanded/index.test.tsx, src/features/Navigation/Navigation.test.tsx, src/test/testStore.tsx
Fix npm run test, by adding wrapper (BrowserRouter) to test renderer (renderWithProviders)
--
=> Add Provider to tests

src/features/Chat/chatPageApi.ts, src/features/Chat/components/ActiveWindow/Header/index.tsx, src/features/Chat/components/ActiveWindow/MessageField.tsx, src/features/Chat/components/ActiveWindow/index.tsx, src/features/MentorPage/mentorPageApi.ts
- Hide Message-Send field if browzing blocked or archived chat
- Show statusmessage of mentor in chat
- Also fix loading-spinner that was introduced after a component refactor
=> Hide MessageField if chat status ok, show statusMessage

src/features/Chat/chatPageApi.ts
=> Fix chat api path

.github/workflows/test.yml, cypress/support/commands.ts, cypress/tests/logout.cy.ts
Re-enables e2e-tests again for the CI
- [Ticket](https://trello.com/c/YmREXJ5Z/945-fix-ci)
E2E test stopped working at some point, probably after the docker development environment for API was implemented. Probably creating the configuration differs now from how creating behaved before.
The problem was that the backend could not connect to the PG-database. 
PG-url is a secret in the repo where the API would connect.
I suppose the DB was already migrated, since it was not setup in the job workflows
Somehow the connection could not be made anymore.
Instead of using this "magic" db, this PR introduces a PG-service that is spun up on the job. The DB is then migrated and backend can then connect to it.
> **Note**: I also skipped again a test that is broken. I thought I fixed this test with …
=> Re-enable e2e tests in ci

src/features/Chat/components/ActiveWindow/MessageField.tsx, src/features/HomePage/components/Announcements.tsx, src/features/HomePage/components/Concepts.tsx, src/features/HomePage/components/FindMentor.tsx, src/features/HomePage/components/Info.tsx, src/features/HomePage/components/NewMessages.tsx, src/features/HomePage/components/NewestMentors.tsx, src/features/HomePage/index.tsx, src/features/Navigation/MobileDropdown/index.tsx, src/features/Navigation/NavigationItems.tsx, src/static/locales/en/home.json, src/static/locales/fi/home.json
- Adds mobile size view for the home page.
Fixes [Home page mobile mode](https://trello.com/c/XfjjcAW1/950-home-page-mobile-mode)
All good!
=> Home page mobile view

src/features/Authentication/userSlice.ts, src/features/HomePage/components/NewestMentors.tsx, src/features/HomePage/components/Welcome.tsx, src/features/HomePage/index.tsx, src/static/locales/en/home.json, src/static/locales/fi/home.json
- Update _You have unread messages_ text.
- The user is shown only the _You have unread messages_ section or the welcome section - not both.
- Fix bugs with mentor cards on the home page.
- Show different welcome section texts to fresh mentees and mentees that are already chatting.
This improves the home page and fixes bugs.
=> Home page fixes

src/features/MentorPage/components/MentorList/MentorCard/Expanded/BasicInfo.tsx, src/features/MentorPage/components/MentorList/MentorCard/Expanded/Header.tsx, src/features/MentorPage/components/MentorList/MentorCard/Expanded/Tag.tsx, src/features/MentorPage/components/MentorList/MentorCard/Expanded/index.tsx, src/features/MentorPage/components/MentorList/MentorCard/List/Header.tsx, src/features/MentorPage/components/MentorList/MentorCard/List/index.tsx, src/features/MentorPage/components/MentorsFilter/MobileSearch/index.tsx, src/features/Navigation/MobileDropdown/index.tsx, src/features/Navigation/Navbar.tsx
Expanded mentorcard looks like the designs in Figma. Menu-button was made more accessible. 
- [Ticket](https://trello.com/c/Md3Y01GJ/974-expanded-mentorcards-mobile-view)
Previously 
Changes were made to make mentorcard look correct in mobile view. 
All buttons should be accessible with minimum screenwidth of 320px. 
=> Expanded mentorcard's mobile view

src/features/Authentication/userSlice.ts, src/features/Chat/components/Menu/Item.tsx, src/features/Chat/index.tsx, src/features/Chat/selectors.ts
Fixes small issues with archiving/blocking conversations.
=> Fix problems with archiving/blocking

src/features/Authentication/userSlice.ts, src/features/Chat/components/ActiveWindow/Header/index.tsx, src/features/HomePage/components/NewestMentors.tsx, src/features/HomePage/components/ProfileWidget.tsx, src/features/HomePage/index.tsx, src/features/MentorPage/components/MentorsFilter/index.tsx, src/features/MentorPage/index.tsx, src/features/MentorPage/mapper.test.ts, src/features/MentorPage/mentorPageApi.ts, src/features/MentorPage/selectors.ts, src/static/locales/en/home.json, src/static/locales/fi/home.json
Profile Widget is a new feature added to mentors Home Page. From Profile Widget mentors can quickly see their avaibility-status ja status message. It also has a link to Profile Page, so mentor can easily go to the page to edit their profile information.
- [Ticket](https://trello.com/c/mAxmplH1/970-profile-widget-on-front-page)
Widget helps navigating mentors to their profile page and see quick overview of their avaibility status.
Does this introduce new warnings or are linter rules suppressed? Why? Is only manual testing …
=> Profile widget for mentors

cypress/fixtures/inputs.ts, cypress/support/commands.ts, cypress/tests/chat.cy.ts, cypress/tests/home.cy.ts, cypress/tests/login.cy.ts, cypress/tests/logout.cy.ts, cypress/tests/mentee.cy.ts, cypress/tests/mentor.cy.ts, cypress/tests/register.cy.ts, src/components/PasswordInput/PasswordInput.tsx, src/features/ProfilePage/components/DisplayNameEditor.tsx, src/features/ProfilePage/components/EmailEditor.tsx, src/features/ProfilePage/components/PasswordEditor.tsx, src/features/ProfilePage/components/PublicInfo.tsx
- Adds e2e tests for both mentee's and mentor's profile page view.
- Fixes bug in findByText Cypress helper function.
Fixes [E2E tests for the Profile page](https://trello.com/c/t2nMlE8c/987-e2e-tests-for-the-profile-page)
We need to assure that our Profile page and its functionality work.
=> Profile page E2E tests

cypress/support/commands.ts, cypress/tests/home.cy.ts, src/features/Chat/components/ActiveWindow/Header/index.tsx
Fixes [BUG: Mentee's display name is missing from Chat window](https://trello.com/c/rVbxK4QT/989-bug-mentees-display-name-is-missing-from-chat-window)
=> BUG: Mentee's display name is missing from Chat window

src/features/Chat/components/ActiveWindow/Header/DesktopButtons.tsx, src/features/Chat/components/ActiveWindow/Header/Search.tsx, src/features/Chat/components/Menu/Header.tsx, src/features/Chat/components/Menu/index.tsx
- Remove unnecessary chat search buttons.
We don't want to have buttons that don't work in our UI.
=> Remove currently unnecessary chat search buttons

src/features/HomePage/index.tsx
- Replace home page background picture with the correct one.
Fixes [Update home view background picture](https://trello.com/c/NvjoZi7c/992-update-home-view-background-picture)
=> Replace home page background picture

src/features/Chat/components/ActiveWindow/Dialogs/ReportDialog.tsx, src/static/locales/en/chat.json, src/static/locales/fi/chat.json
- Update the report modal texts
Fixes [Update Report dialog texts](https://trello.com/c/xYISYlqK/846-update-report-dialog-texts)
I noticed that we are missing parts of the report feature so I made new Trello tasks for them.
- [Report modal error handling and field validation](https://trello.com/c/wyHYeRc1/998-report-modal-error-handling-and-field-validation)
- [E2E tests for report feature](https://trello.com/c/vuZm3I0o/999-e2e-tests-for-report-feature)
=> Update report dialog texts

src/components/Toaster/Toast.tsx, src/features/Authentication/authenticationApi.ts, src/features/Chat/chatPageApi.ts, src/features/MentorPage/mentorPageApi.ts
Don't show multiple notifications with identical content.
Fixes [Don't show duplicate notification](https://trello.com/c/4d5oXOjA/991-dont-show-duplicate-notification)
=> Don't show duplicate notification

.github/scripts/start-api, cypress/tests/chat.cy.ts, cypress/tests/report.cy.ts, src/components/Buttons/Button.tsx, src/components/Buttons/StatusButton.tsx, src/components/Dialog/Dialog.tsx, src/components/Toaster/Toast.tsx, src/components/constants.ts, src/features/Authentication/userSlice.ts, src/features/Chat/chatPageApi.ts, src/features/Chat/components/ActiveWindow/Dialogs/ReportDialog.tsx, src/features/Chat/components/ActiveWindow/Dialogs/ReportSuccessDialog.tsx, src/features/Chat/components/ActiveWindow/Header/DesktopButtons.tsx, src/features/Chat/components/ActiveWindow/Header/Search.tsx, src/features/Chat/components/ActiveWindow/Header/TabletButtons.tsx, src/features/Chat/components/ActiveWindow/Header/index.tsx, src/features/Chat/components/ActiveWindow/MessageField.tsx, src/features/Chat/components/Menu/Header.tsx, src/features/Chat/validators.test.ts, src/features/Chat/validators.ts, src/features/MentorPage/components/MentorList/MentorCard/Expanded/Content.tsx, src/features/MentorPage/components/MentorList/MentorCard/Expanded/Header.tsx, src/features/ProfilePage/components/DisplayNameEditor.tsx, src/features/ProfilePage/components/EmailEditor.tsx, src/features/ProfilePage/components/PasswordEditor.tsx, src/static/locales/en/chat.json, src/static/locales/fi/chat.json
- Fixes report modal.
- Adds input validation.
- Shows error notifications.
- Refactors icon sizing.
Fixes:
- [Report modal error handling and field validation](https://trello.com/c/wyHYeRc1/998-report-modal-error-handling-and-field-validation)
- [E2E tests for report feature](https://trello.com/c/vuZm3I0o/999-e2e-tests-for-report-feature)
=> Report modal

src/features/HomePage/components/Welcome.tsx
Make admin UI link skip client side routing.
Fixes # Admin link
Admin link should be functional.
=> Fix admin link on home page

src/features/About/index.tsx, src/static/locales/en/common.json, src/static/locales/fi/common.json
Description was added to about modal. 
- [Ticket](https://trello.com/c/bRjptuVZ/1017-add-service-description-to-the-about-modal)
Fixes # No service description
Before there was only info about the app not the service.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
=> Add service description

cypress/support/commands.ts, cypress/tests/login.cy.ts, cypress/tests/mentee.cy.ts, cypress/tests/mentor.cy.ts, src/login/index.html, src/login/index.js, src/login/styles.css, src/register/index.html, src/register/styles.css, src/static/styles/static-pages.css, webpack.config.js
Fix login and registration pages.
Login and registration pages were broken when deployed to a live env.
=> Fix login and registration pages

src/static/localization.js
Fix login and registration page locales.
Login and registration page locales are not found in live env.
=> Fix login and registration locales

cypress/support/commands.ts, cypress/tests/register.cy.ts, src/login/index.html, src/login/styles.css, src/register/index.html, src/register/index.js, src/register/styles.css, src/static/localization.js, webpack.config.js
Use web login on the registration page and enable autologin.
Autologin was desired.
=> Implement autologin

src/features/MentorPage/components/MentorList/MentorCard/Expanded/BasicInfo.tsx, src/features/MentorPage/components/MentorList/MentorCard/Expanded/Content.tsx, src/features/MentorPage/components/MentorList/MentorCard/Expanded/Languages.tsx, src/features/MentorPage/components/MentorList/MentorCard/List/Header.tsx, src/features/MentorPage/components/MentorList/MentorCard/List/index.tsx
Fixes [Profile card layout issues](https://trello.com/c/FEKQMSiL/1020-profile-card-layout-issues)
=> Profile card layout issues

src/features/About/LicenseList.tsx, src/features/About/index.tsx, src/static/locales/en/common.json, src/static/locales/fi/common.json
- License modals service description has paragraph division
- Licenses div has more height in mobile view
- In mobile view added spacing for licenseslist so it is easier to read
- Changed it so licenses name is a link to project site (to avoid too long urls)
- Added padding to description and to licenses for prettier and more aligned look
- [Ticket](https://trello.com/c/8WKHOj6D/1053-improve-about-modal)
Fixes # Licenses Modal was ugly
Does this introduce new warnings or are linter rules suppressed? Why? Is only manual testing applicable for this feature? Is there something …
=> Improve license modal

cypress/tests/chat.cy.ts, src/features/Chat/chatPageApi.ts, src/features/Chat/components/ActiveWindow/MessageField.tsx, src/features/Chat/components/ActiveWindow/index.tsx, src/features/Chat/selectors.ts
- Clear message drafts when changing conversation
- Fix messaging bugs
- Add e2e test
- Refactor e2e test file
Fixes [Unsent message draft is not cleared when changing between chats](https://trello.com/c/SQYQZ1Nd/1055-unsent-message-draft-is-not-cleared-when-changing-between-chats)
=> Message drafts

src/features/Chat/components/ActiveWindow/Message.tsx
Improve the bubble - to distinguish sent and received.
Since there was no color-change in design - i opted out to not implement anything out of my ... hat
I think now it is way better and not that confusing
Fixes # ([issue](https://trello.com/c/ursn5mKp/1081-improve-chat-message-bubble-styling))
=> Set max-width for message-bubbles

package.json, src/static/locales/en/profile.json, src/static/locales/fi/profile.json
Improve text for vacation mode, to make it clear to mentors
Fixes # (https://trello.com/c/EPAQrsJS/1059-fix-absence-status-description-text)
=> Improve vacation-mode helper text

src/static/locales/en/common.json, src/static/locales/fi/common.json
Give feedback link redirects to the actual feedback-url
Fixes # ([issue](https://trello.com/c/pSCrRSi2/1071-fix-anna-palautetta-button-to-actual-feedback-form))
Bug fix
=> Fix feedback-url

src/landing/index.html, src/landing/styles.css, src/register/styles.css
Make register page responsive
Fixes # ([issue](https://trello.com/c/R78EaJXu/669-registration-page-mobile-view))
Additionally decreasing the default-paragraph size on landing-page
For allowing new users register from web easily if using small screens
- [] I have commented my code, particularly in hard-to-understand areas
=> Improve register form responsiveness

src/components/Toaster/index.tsx
Autoclose successful notification after 4 seconds.
=> Make successful notifications disappear

cypress/tests/home.cy.ts, src/features/Authentication/selectors.ts, src/features/HomePage/components/Welcome.tsx, src/static/locales/en/home.json, src/static/locales/fi/home.json
=> Fix home page content

src/features/HomePage/components/NewestMentors.tsx, src/features/MentorPage/components/MentorList/MentorCard/List/index.tsx
- Added max-width to mentor card, so it is displayed correctly. 
- Centered newest mentor -title
Fixes # ([issue](https://trello.com/c/WVjnkJST/1092-mentor-cards-too-wide-on-home-page))
and makes the component closer to figmas design
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to …
=> Add max-width to mentor card

src/App.tsx
With white bg, the spinner is the dark-variant
Fixes # ([issue](https://trello.com/c/iKUfR0Sb/1095-fix-initial-loading-spinner))
The spinner was not visible
=> Fix app-spinner color

src/components/Footer/Footer.tsx, src/components/Link/index.tsx, src/features/About/index.tsx, src/features/HomePage/components/Concepts.tsx, src/features/Navigation/InfoDropdown/index.tsx, src/features/Navigation/LogoContainer.tsx, src/features/Navigation/MobileDropdown/index.tsx, src/landing/index.html, src/landing/index.js, src/landing/styles.css, src/static/links.json, src/static/locales/en/common.json, src/static/locales/fi/common.json
Add 
- link to slk site from landing page footer
- add link to slk site from spa-application footer
- add link to slk-ylitse-mentorapp -page from navbar
- add link to slk-ylitse-mentorapp -page from about modal
Additionally moved some hardcoded links and links from translations to links.json
Fixes # ([issue](https://trello.com/c/2zis9EnB/1079-link-slk-logo-to-sos-lapsikylafi-on-landing-page-and-others))
Does this introduce new warnings or are linter rules suppressed? Why? Is only manual testing applicable for this feature? Is there something special that the reviewer should …
=> Add link to slk site from footer

src/components/Chip/Chip.tsx, src/features/MentorPage/components/MentorList/index.tsx, src/features/MentorPage/components/MentorsFilter/MentorSearch/index.tsx, src/features/MentorPage/components/MentorsFilter/MobileSearch/index.tsx, src/features/MentorPage/components/MentorsFilter/Skills/BottomBar/MobileBottomBar.tsx, src/features/MentorPage/components/MentorsFilter/Skills/index.tsx, src/features/MentorPage/components/MentorsFilter/index.tsx
Adds all the existing search features to mobile view. 
In addition fixes styling with skill-chips to match designs.
Fixes # ([1106](https://trello.com/c/gUDQz5a5/1106-fix-mentor-search-filtering-in-mobile-mode))
Makes client consistent in both desktop and mobile view. 
=> Fix mentor search mobile mode

src/landing/index.html, src/landing/styles.css
Added landing page styling for big desktop
=> 1105: Landing page styling for big desktop

src/landing/index.html, src/landing/styles.css, src/static/styles/variables.css
We wanted the Ylitse-banner to stand out better from the header. Therefore the header background color is changed to ligher color and banner has added shadows. Also different sections on the main landing page have now separate background colors so they stand out from each other. 
In addition corrects content on page from 'yli 5000 aktiivista keskustelua' to 'yli 5000 käytyä keskustelua'. 
Fixes # ([1126](https://trello.com/c/DmMc0qrh/1126-fix-landing-page-background-colors) + missing pieces from [1113](https://trello.com/c/dmsF37zX/1113-landing-page-content-changes))
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant …
=> Fix landing page background colors

src/landing/styles.css
User can now scroll mentor cards in mobile view
Fixes # ([1122](https://trello.com/c/E2tEvWUf/1122-mentor-card-scrolling-on-landing-page-in-mobile-mode))
=> Scroll mentorcards in mobile view

src/features/MentorPage/components/MentorList/MentorCard/List/index.tsx, src/landing/styles.css
Mentor cards now have shadows so they match designs in Figma and are more visible from the background.
Fixes # ([1129](https://trello.com/c/tfEH60b3/1129-add-shadows-to-mentor-cards))
=> Add shadows to mentor cards

src/landing/index.html, src/landing/styles.css
Renames classes for mobile app ad so it does not trigger ad blockers
Fixes # ([1130](https://trello.com/c/TkuVQ4PU/1130-rename-mobile-app-ad-classes))
- [] I have commented my code, particularly in hard-to-understand areas
=> Rename mobileapp ad classes

src/landing/styles.css
Fixes propotions of mobile app ad. 
Fixes # ([1080](https://trello.com/c/rhUA84Z6/1080-mobile-app-ad-on-landing-page))
=> Fix propotions of mobile app ad

cypress/tests/home.cy.ts, src/features/HomePage/components/WelcomeMessage.tsx, src/features/HomePage/index.tsx, src/hooks/useManualComponentShow.ts, src/login/index.js, src/register/index.js, src/static/locales/en/home.json, src/static/locales/fi/home.json
Shows a welcome message in the homepage to the user when they login or register. Message disappears when user navigates out of the home page or refreshes the page. 
Fixes # ((1061)[https://trello.com/c/9ANVn6j2/1061-welcome-message-on-the-home-page])
This way we can greet the user when they login/register.
=> Welcome message on the home page

src/static/locales/en/landing.json, src/static/locales/fi/landing.json
Changes first text user sees on landing page.
Fixes # ([1184](https://trello.com/c/8x345Zbe/1184-landing-page-text-change))
The new text is more straightforward and user friendly. We want to guide new possible users better to understand the service.
=> Landing page text change

src/features/HomePage/components/Welcome.tsx, src/features/Navigation/Navbar.tsx, src/static/locales/en/common.json, src/static/locales/fi/common.json
Make link to local admin UI work correctly.
=> Fix local admin link
