sos-lapsikyla/ylitse-web

src/login/styles/ylitse.css

Some screen sizes caused problems because "vh margins". This pr fixes the problems by replacing the problematic vh margins by pixels.
For example 
Some screen sizes were broken.
Existing tests

Fix margins which caused problems in some screen sizes

---

package-lock.json

Update vulnerable terser library. Libraries show audit error if otherwise if `npm i` is run.
To keep libraries up to date.
Tests pass after installation.
-

Update packages according to audit fix

---

cypress/support/commands.ts
cypress/tests/register.cy.ts
src/register/index.html
src/register/index.js

Fixes: 
[Improve input field validation](https://trello.com/c/ElZidpPb/713-improve-input-field-validation)
[Registration page inputs should show errors ONLY if they have been visited](https://trello.com/c/Poi4Hqu6/709-registration-page-inputs-should-show-errors-only-if-they-have-been-visited)
To improve usability.

Validate inputs after every keyup, and do it only to inputs already touched

---

cypress/support/commands.ts
cypress/tests/register.cy.ts
src/register/index.html
src/register/index.js

Password confirmation error is shown only after the field has been accessed. Input field validations are triggered on blur instead of keyup so that when using keyboard navigation, the error is displayed after the field is left and not right when it's accessed. 
Fixes [Password confirmation input should show error ONLY if it has been visited](https://trello.com/c/ZgJIq0nU/715-password-confirmation-input-should-show-error-only-if-it-has-been-visited)
This improves usability and UX.

Fix password confirmation error

---

src/features/Chat/chatSlice.ts
src/features/Chat/components/ActiveWindow/index.tsx
src/features/Chat/components/Menu/Item.tsx
src/features/Chat/index.tsx
src/features/HomePage/components/NewMessages.tsx

- Chats are sorted in descending order by most latest message timestamp.
- Navigating to the Chat page opens the latest chat with unread messages. If no chat has unread messages, the chat with the latest message is displayed.
Fixes:
- [Open latest chat on chat page](https://trello.com/c/TZiw0sDz/948-open-latest-chat-on-chat-page)
- [Sort chats by latest message timestamp](https://trello.com/c/ImDqc3di/951-sort-chats-by-latest-message-timestamp)
Does this introduce new warnings or are linter rules suppressed? Why? Is only manual testing applicable for this feature? Is there …

Open latest chat on chat page + Sort chats by latest message timestamp

---

src/components/Buttons/IconButton.tsx
src/components/TextInput/TextInput.tsx
src/features/Chat/components/ActiveWindow/MessageField.tsx
src/features/Chat/components/ActiveWindow/index.tsx

- Disable message field and send button between sending message and updating chat history.
- Show written message in message field until messages have been updated.
Fixes [Fix sending chat messages](https://trello.com/c/IdKzo18U/953-fix-sending-chat-messages)
- To improve the usability of the application.

Fix sending messages

---

.github/workflows/test.yml
README.md
cypress.config.ts
cypress/fixtures/accounts.ts
cypress/support/api.ts
cypress/support/commands.ts
cypress/tests/chat.cy.ts
cypress/tsconfig.json
package-lock.json
package.json
src/App.tsx
src/features/Authentication/userSlice.ts
src/features/Chat/chatPageApi.ts
src/features/Chat/chatSlice.ts
src/features/Chat/components/ActiveWindow/Header/DesktopButtons.tsx
src/features/Chat/components/ActiveWindow/Header/TabletButtons.tsx
src/features/Chat/components/ActiveWindow/Header/index.tsx
src/features/Chat/components/ActiveWindow/Message.tsx
src/features/Chat/components/ActiveWindow/MessageField.tsx
src/features/Chat/components/ActiveWindow/index.tsx
src/features/Chat/components/Menu/Item.tsx
src/features/Chat/components/Menu/index.tsx
src/features/Chat/index.tsx
src/features/Chat/mappers.ts
src/features/Chat/selectors.ts
src/features/HomePage/index.tsx
src/features/Navigation/MobileDropdown/MobileNavItem.tsx
src/features/Navigation/MobileDropdown/index.tsx
src/features/Navigation/NavigationItems.tsx
src/hooks/useIsVisible.ts

Improves message-fetching logic, and logic for marking messages unseen and add some e2e tests to verify behaviour
- if initial-message fetch includes unread-messages, keep fetching until get a response with no unread, or all messages are fetched
- mark messages unseen only when they have been fully visible for 1 second
Similar fixes to logic were made to mobile app few months ago, keep the feature parity
Added new e2e-test suite for chats. 
- [] Unittest
NA

Improve message fetching

---

cypress/tests/mentor.cy.ts
src/features/HomePage/components/NewestMentors.tsx

Newest mentors mentorcards are now scrollable, and users can see both cards also in mobile view. 
- [Ticket](https://trello.com/c/oD9OIVg1/990-bugfix-make-newest-mentors-scrollable-in-mobile-view)
Newest mentors mentorcards were not scrollable in mobile view and therefore users could not access the feature correctly.

Make newest mentor cards scrollable in mobile view

---

cypress/support/commands.ts
cypress/tests/mentor.cy.ts
src/components/Chip/Chip.tsx
src/components/DropdownSearch/DropdownSearch.tsx
src/components/DropdownSearch/index.ts
src/components/SearchBar/SearchBar.tsx
src/components/Text/variants.ts
src/features/Chat/selectors.ts
src/features/HomePage/index.tsx
src/features/MentorPage/mentorPageApi.ts
src/features/MentorPage/selectors.ts
src/features/ProfilePage/components/PublicInfo.tsx
src/features/ProfilePage/components/SkillsEditor.tsx
src/utils/utils.ts

- Mentors' skills are displayed on the Profile page.
- Mentor can search for skills using the dropdown search.
- Mentor can add and remove skills.
Fixes Trello tasks: 
- [Profile page mentor skills: displaying, searching, adding and removing skills](https://trello.com/c/1St9pc7R/977-profile-page-mentor-skills-displaying-searching-adding-and-removing-skills)
- [Flaky mentor e2e test](https://trello.com/c/L7w8wjJS/995-flaky-mentor-e2e-test)
Mentors need to be able to add and remove skills from their profile.

Mentors can update their skills on the profile page

---

package.json
webpack.config.js

Licenses are now created when running `npm run start` and `npm run build`, so licenses are included in builds and generate now warnings. Licenses are copied to dist folder.
Licenses were missing from build.
- [] Any dependent changes have been merged and published in downstream modules

Fix license bundle

---

.eslintignore
src/features/Authentication/userSlice.ts
src/utils/http.ts

Use webrefresh to refresh token
Here is the [API PR](https://gitlab.com/ylitse/ylitse-api/-/merge_requests/80) 
[Trello-ticket](https://trello.com/c/XfxGaRjH/979-implement-webrefresh-flow)
When using app, user should not be thrown out, but access refreshed
See recording how it works in action
(accesstoken ttl 5 sec, refreshtoken ttl 15 sec)
https://github.com/user-attachments/assets/d4ec378c-648d-4f68-949e-c7b2bd38a485
I tested this by setting minimal token lifetime and saw that after access was invalid, then the refresh-flow worked
NA

Use webrefresh

---

cypress/tests/chat.cy.ts
src/features/Chat/components/ActiveWindow/Header/DesktopButtons.tsx
src/features/Chat/components/ActiveWindow/Header/TabletButtons.tsx
src/features/Chat/components/ActiveWindow/Header/index.tsx
src/static/locales/en/chat.json
src/static/locales/fi/chat.json

Fixed misleading texts when user is blocked. New changes are more explicit about the action made. I have added new dialog variant 'unblock', so now user knows when they are unblocking someone rather than just restoring conversation. It is still told that if user decides to unblock the other user, conversation will be restored. 
- [Ticket](https://trello.com/c/kcfFBJFW/1016-change-block-and-archive-button-and-confirmation-texts)
Fixes # Misleading texts when unblocking user
Texts should be explicit about actions
- [] New feature (non-breaking change which adds functionality) …

Change block and archive texts

---

cypress/tests/chat.cy.ts
src/features/Chat/components/ActiveWindow/Header/index.tsx

- Chat is closed after user has blocked it.
- Fixes test _will not show unseen dot for new messages in blocked conversation_.
Fixes [Navigate away from the chat after it has been blocked](https://trello.com/c/fwhaKw86/1015-navigate-away-from-the-chat-after-it-has-been-blocked)
We don't want the user to see further messages from a contact they have blocked.

Navigate away from the chat after it has been blocked

---

cypress/tests/chat.cy.ts
src/features/MentorPage/components/MentorList/MentorCard/Expanded/Content.tsx

- Disable _Start conversation_ button on mentor's own profile card.
- Fix desktop mentor card languages styling by using the correct mentor id in the code.
Fixes [Mentor should not be able to discuss with themselves (Client)](https://trello.com/c/TQOyfvmF/1014-mentor-should-not-be-able-to-discuss-with-themselves-client)
We don't want to allow mentors starting conversations with themselves.

Mentor should not be able to discuss with themselves (Client)

---

src/features/MentorPage/components/MentorsFilter/Skills/BottomBar/index.tsx
src/features/MentorPage/components/MentorsFilter/index.tsx

Fixes [Hide pagination buttons if there is only one page in mentor search](https://trello.com/c/p6psWul0/1019-hide-pagination-buttons-if-there-is-only-one-page-in-mentor-search)

Hide pagination buttons if there is only one page in mentor search

---

src/features/Chat/components/ActiveWindow/Message.tsx

- Respect message whitespace when displaying them. 
Fixes [Whitespace is ignored when rendering chat messages](https://trello.com/c/LSSECt0X/1021-whitespace-is-ignored-when-rendering-chat-messages)

Keep message whitespace when displaying it to the user

---

cypress/tests/chat.cy.ts
src/features/Chat/components/ActiveWindow/MessageField.tsx

- Trim leading and trailing whitespace before sending message
- Disable sending if text field does not have any non-whitespace characters
- Add e2e test
Fixes [Prohibit sending empty chat messages](https://trello.com/c/NVotSqEE/1042-prohibit-sending-empty-chat-messages)

Prohibit sending empty chat messages

---

src/features/MentorPage/components/MentorList/MentorCard/Expanded/Content.tsx

If starting a conversation, disable the button if mentor is on vacation-mode.
Existing conversations are not affected
Fixes # ([issue](https://trello.com/c/yKCgbkBM/1056-actor-can-start-a-chat-with-a-vacationing-absent-mentor))
Bug fix

Disable start-conversation-button if vacationing mentor

---

src/static/locales/en/register.json
src/static/locales/fi/register.json

Changed text in registration page.
The service is meant for people over 17 years of age, not 15
Fixes # ([issue](https://trello.com/c/KpxF7GsC/1070-fix-register-page-age-limit-in-the-switch-button-15-17))
Correct service information

Change localization age-limit 15 to 17 year old

---

src/features/Chat/components/ActiveWindow/MessageList.tsx

Remove auto-scroll on new messages because of a bug ( if user scrolls the conversation themselves auto-scroll will scroll to the middle of the container when new messages come )
- Still auto-scroll on initial opening of the conversation
- When "you got new messages"-design for conversation is done, rework the scrolling logic
Fixes # ([issue](https://trello.com/c/Cj80tpKW/1068-disable-auto-scroll))
https://github.com/user-attachments/assets/3771b384-856d-4af7-87bb-0b5559478fa4
Bug fix
Does this introduce new warnings or are linter rules suppressed? Why? Is only manual testing …

Remove auto-scroll on new messages

---

cypress/tests/chat.cy.ts
src/features/Chat/chatPageApi.ts
src/features/Chat/chatSlice.ts
src/features/Chat/components/ActiveWindow/Header/index.tsx
src/features/Chat/constants.ts
src/static/locales/en/chat.json
src/static/locales/fi/chat.json

Unblocking and unarchived notification was the same and therefore not effective in communicating the exact change in status. Updated to have separate notifications, so users don't get confused.
Fixes # ([issue](https://trello.com/c/3uT01UzJ/1054-change-block-and-archive-notification-texts))
To have actions and notifications in line.
- [] I have made corresponding changes to the …

Fix unblock notification

---

src/features/HomePage/components/Concepts.tsx

Concepts texts were overflowing in mobile view. Fixed code so if text is too long it gets wrapped and stays inside of the container. Result:
Fixes # ([issue](https://trello.com/c/q3MiFZL4/1097-concepts-text-overflowing-from-its-container-in-mobile-view))
BugFix

Fix overflowing concepts in mobile view

---

src/baseApi.ts
src/components/Text/variants.ts
src/features/About/apiVersionApi.ts
src/features/About/index.tsx
src/features/HomePage/components/ProfileWidget.tsx
src/features/Navigation/InfoDropdown/InfoItem.tsx
src/static/locales/en/common.json
src/static/locales/fi/common.json

Use API - version-endpoint to show the version of API
- Also additional fix, use spans inside a-elements, since if we nest a:s its not correct and we get annoying console-warning.
Fixes # ([issue](https://trello.com/c/1a5eDAOO/1090-use-api-version-on-about-modal))
Before we just show "2.0"

Show api-version from version endpoint

---

cypress/fixtures/accounts.ts
cypress/tests/login.cy.ts
cypress/tests/mentee.cy.ts
src/features/Authentication/models.ts
src/features/ProfilePage/components/EmailEditor.tsx

With old-old users, it is possible that the email-property is missing. Make the codec similar than in [moblle-app](https://github.com/sos-lapsikyla/ylitse-app/blob/master/src/api/account.ts)
Fixes # ([issue](https://trello.com/c/PwOayr5J/1094-make-email-optional-in-account-schema))
For example, the old admin-user was not able to login to web

Set email as partial for accountCodec

---

cypress/tests/mentors.cy.ts
src/features/MentorPage/components/MentorsFilter/MentorSearch/index.tsx
src/features/MentorPage/mentorsFilterSlice.ts

Improvement of MentorSearch-component:
- "Poista suodattimet" -button resets only skill-filters
- Added reset button for search bar
- Search bar is now centered
- [Ticket](https://trello.com/c/ZGsGSPVK/1091-mentorsearch-component-improvement)
"Poista suodattimet" was not intuitive and also reset search bar. Changes match designs in Figma. 
- [] I have commented my code, …

Improve mentor search component

---

src/features/Chat/components/ActiveWindow/Message.tsx

Chat bubbles were too close to each other so I added some bottom margin to the containers.
Fixes # 1089
https://trello.com/c/MGf0ErhT/1089-message-bubbles-too-close-to-each-other
To separate the chat bubbles and make it clearer what message the timestamps were part of
Visually tested that the margins were there

1089 - Chat bubble spacing fix

---

src/features/Navigation/InfoDropdown/index.tsx

The info dropdown menu did not close when a sub-menu item was clicked. Changed so that the menu is closed when the item is clicked.
Fixes # 1007
[https://trello.com/c/EDAU1uQ7/1007-closing-a-modal-will-leave-navigation-menu-open](https://trello.com/c/EDAU1uQ7/1007-closing-a-modal-will-leave-navigation-menu-open)
The menu dropdown was still open after an item had been clicked and the focus was moved to modal that had been opened

1007 - Closing the info navigation when link modal is opened

---

src/features/Confirmation/ButtonGroup.tsx
src/features/Confirmation/Dialog.tsx

The notification dialog styling was different between the report user and archive dialogs. The button alignment was depending on the contents text length and row count. Also the dialogs height was fixed so it did not grow depending on the amount of text.
Fixes # 1025
https://trello.com/c/PjI9rKUy/1025-fix-notification-styles

1025 - Notification styles fixes

---

src/features/Chat/components/ActiveWindow/ScrollToBottomButton/useBottomAction.ts

Improve chat scrolling behaviour:
1. if a new message appears and user is on the bottom, there will be automatic scroll
2. Another scenario: We have scrolled to the middle of the content. If new message appears, we dont automatically scroll to the bottom.
Fixes # ([issue](https://trello.com/c/LpZr0ja5/1064-chat-does-not-scroll-to-the-newest-message))
The video demonstrates this fix maybe better than my writing.
You can also see the scroll-to-bottom-button briefly flashing on the messages list when a new message appears and the auto-scroll takes effect.
That I'll fix too, but just atm I don't have a nice idea how to fix it, so I need to sleep on it.
https://github.com/user-attachments/assets/c698865f-6bcf-419c-943d-4eaa967760dc
Please describe …

Add scrolling follower if already on bottom
